### DISCUSSION TITLE
Spellcheck Not Working

### DISCUSSION THREAD

**Discussion by skullsplice** [tiredofit/docker-collabora-online#18] [Q&A]
Hello all,

I've been using this container allot recently. I used to rely on Collabora/Code but ran into issues with the 20 document limit.

However, I haven't been able to get spell check to work. I have miss-spelled words in this open document but nothing is being underlined. These are the spelling options dialogs from within libre-office online:

![Screenshot from 2021-09-12 17-45-56](https://user-images.githubusercontent.com/78186191/133009003-1e5f039d-bc9c-4278-8cfa-eb98d4b0f10e.png)
![Screenshot from 2021-09-12 17-45-43](https://user-images.githubusercontent.com/78186191/133009012-b99a8e26-2253-49ae-80af-1fdf4f5732d8.png)

This is my docker-compose file:

```
version: '3.7'
services:

  libreoffice-app:
    image: tiredofit/libreoffice-online:latest
    hostname: libreoffice\.myhost\.net
    container_name: libreoffice-app
    expose:
      - 9980
    cap_add:
      - MKNOD
    environment:
      - VIRTUAL_HOST=libreoffice\.myhost\.net
      - VIRTUAL_NETWORK=proxy
      - VIRTUAL_PORT=9980
      - VIRTUAL_PROTO=http
 
      - CONTAINER_NAME=libreoffice-app
      - INTERFACE=notebookbar
      - ADMIN_USER=admin
      - ADMIN_PASS=replaced
      - ALLOWED_HOSTS=myhost.net
      - DICTIONARIES=en_GB,en_US
      - LOG_LEVEL=warning
    volumes:
      - "~/docker/libreoffice-online/logs:/var/log/loolwsd"
      - "~/docker/libreoffice-online/assets:/assets/custom"
    networks:
     App_Stack:
       ipv4_address: 172.0.0.9
    ports:
     - 980:9980
    restart: always

networks:
  App_Stack:
    external: true
```

Thank you for all of your hard work maintaining container. Any assistance would be greatly appreciated!
