### ISSUE TITLE
allowed hosts ^(.*)\.example\.org doesn't work any longer

### ISSUE THREAD

**Issue by joergmschulz** [tiredofit/docker-collabora-online#21]
### Summary
until some versions ago, the stanza `^(.*)\.example\.org` could be used for the ALLOWED_HOSTS. 
Now, the FIRST host matching this pattern will be allowed, all following denied. Thus, it is not possible to use one docker for multiple hosts.
The solution is to use groups in coolwsd.xml / didn't find the syntax yet.

1st  update: the coolwsd.xml section for multiple hosts looks like:
```
<alias_groups desc="default mode is 'first' it allows only the first host when groups are not defined. set mode to 'groups' and define group to allow multiple host and its aliases" mode="groups">
            <!-- If you need to use multiple wopi hosts, please change the mode to "groups" and
                    add the hosts below.  If one host is accessible under multiple ip addresses
                    or names, add them as aliases. -->
            <group>
                    <host desc="hostname to allow or deny." allow="true">https://server1.yourdomain.de:443</host>
                    <host desc="hostname to allow or deny." allow="true">https://secondnameforserver1.yourdomain:443</host>
                    <!-- <alias>scheme://aliasname1:port</alias>
                    <alias>scheme://aliasname2:port</alias> -->
            </group>
            <group>
                    <host desc="hostname to allow or deny." allow="true">https://server2.yourdomain.de:443</host>
            </group>
            <!-- More "group"s possible here -->
</alias_groups>
```

**Comment by tiredofit** [comment]
I'm not having any success loading this new image `2.3.6` on a Nextcloud 23.0.3 install. And you? 
We can certainly adjust this to make the accepted hosts work, just need a few known good configs to build upon.

**Comment by joergmschulz** [comment]
Yesterday, I made it work with the restriction above (only first host connects). Out of the box.

```
services:
  office2:
    image: tiredofit/collabora-online
    container_name: office2.${DOMAIN}.de
    hostname: office2.${DOMAIN}.de
    # expose:
      # - 9980
    cap_add:
      - MKNOD
      - NET_ADMIN
      - SYS_CHROOT
      - FOWNER
    privileged: true
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:office2.${DOMAIN}.de
      - traefik.http.services.office2.loadbalancer.server.port=9980
      - "traefik.http.routers.office2.rule=Host(`office2.somedomain.de`, `office2.yourdomain.de`)"
      - "traefik.http.routers.office2.tls=true"
      - "traefik.docker.network=traefik"
      - traefik.office2.backend=office2

    volumes:
      - /data/${DOMAIN}/office2/logs:/logs
      - /data/${DOMAIN}/office2/fonts:/assets/custom-fonts
    environment:
      - CONTAINER_NAME=office2.${DOMAIN}.de
      - TIMEZONE=Europe/Berlin

      - ADMIN_USER=js
      - ADMIN_PASS=welovepasswordswithescaped$$signsmaybebetterputthisintotheDotEnvFile
      - ALLOWED_HOSTS=^(.*)\.yourdomain.de
      - AUTO_SAVE=30
      - DICTIONARIES=de,fr
      - "DONT_GEN_SSL_CERT=set"
      - ENABLE_CLEANUP=true
      - ENABLE_TLS=FALSE
      - ENABLE_TLS_REVERSE_PROXY=TRUE
      - INTERFACE=notebookbar
      - "LANGUAGE=de_DE en_GB en_US fr_FR"
      - LOG_LEVEL=error

      - "extra_params=--o:ssl.enable=false --o:ssl.termination=true --o:user_interface.mode=notebookbar --o:welcome.enable=false --o:user_interface.TextStatusbar=false"
    networks:
      traefik:
      services:
        ipv4_address: ${OFFICE_IP}
    restart: unless-stopped



networks:
  traefik:
    external: true
  services:
    external: true

```
I'm getting many messages like
`frk-01559-01559 2022-03-24 08:45:50.381682 +0100 [ forkit ] ERR  #18: read failed, have 0 buffered bytes (EAGAIN: Resource temporarily unavailable)| net/Socket.hpp:1123`
which I haven't seen before. Other than that, it's working.


One downside in comparison to the CODE version is: they added some magic to inherit the nextcloud css/templates. Maybe it would be a good idea to not compile our own cool but use the code image as base.
