### ISSUE TITLE
Application cant be started

### ISSUE THREAD

**Issue by Tresillo2017** [tiredofit/docker-collabora-online#44]
### Summary

Every time I try to start the app I get spammed with an error on the console

### Steps to reproduce

Run the image using my compose.yml config provided

### What is the expected *correct* behavior?

To run

### Relevant logs and/or screenshots

```
collabora  | Collabora Office 24.04 - Fatal Error: The application cannot be started.
collabora  | User installation could not be completed.
collabora  | notcoolmount: unmount failed to detach [/opt/cool/child-roots/1206-4334f913/uSraksA7N4Hcn1l9/lo]: Operation not permitted.
collabora  | notcoolmount: forced unmount of [/opt/cool/child-roots/1206-4334f913/uSraksA7N4Hcn1l9/lo] failed: Operation not permitted.
collabora  | notcoolmount: unmount failed to detach [/opt/cool/child-roots/1206-4334f913/uSraksA7N4Hcn1l9]: Operation not permitted.
collabora  | notcoolmount: forced unmount of [/opt/cool/child-roots/1206-4334f913/uSraksA7N4Hcn1l9] failed: Operation not permitted.
```

### Environment

All off nextcloud data is on a nfs share mounted with the right permisions for the nextcloud container
``//redacted/nextcloudaio /mnt/ncdata/ cifs rw,mfsymlinks,seal,credentials=/etc/credentials,uid=1000,gid=1000,file_mode=0770,dir_mode=0770 0 0``
I'm using an external proxy (swag)

- Image version / tag: [latest](https://hub.docker.com/layers/tiredofit/collabora-online/latest/images/sha256-7a2de326a12ef83540bef60e800430e842e4f1b80526f82f676673aac5d12f63?context=explore)
- Host OS: Debian `Linux docker 6.1.0-23-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.99-1 (2024-07-15) x86_64 GNU/Linux` VM

<details>
<summary>Any logs | docker-compose.yml</summary>

```yaml
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - $PWD/config:/config
      - /mnt/ncdata:/data
    ports:
      - 8089:443
      - 8088:80
    restart: unless-stopped
    depends_on:
      - db

  collabora:
    image: tiredofit/collabora-online
    container_name: collabora1
    privileged: true
    environment:
      - TIMEZONE=Europe/Madrid
      - CONTAINER_NAME=collabora
      - ADMIN_USER=redacted
      - ADMIN_PASS=redacted
      - ALLOWED_HOSTS=cloud.tomasps.com
      - ENABLE_TLS=FALSE
      - ENALBE_TLS_REVERSE_PROXY=TRUE
      - INTERFACE=notebookbar
      - LOG_TYPE=FILE
    ports:
      - 9980:9980
    volumes:
      - ./collogs:/logs/
    restart: unless-stopped

  db:
    image: mariadb:latest
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW --character-set-server=utf8
    volumes:
      - $PWD/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=redacted
      - MYSQL_PASSWORD=redacted
      - MYSQL_DATABASE=redacted
      - MYSQL_USER=redacted
```

</details>
